name: material_playground
description: A place to tweak your theme and see how it affects material widgets. Vendored from flex_color_scheme
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flex_color_picker: ^3.2.0
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true
